export const GUMROAD_SEARCH_QUERIES = [
  "vrchat tool",
  "vrchat system",
  "vrchat script",
  "vrchat udon",
  "vrchat unity",
  "vrcfury",
  "modular avatar",
  "vrchat shader",
  "vpm",
  "unitypackage vrchat",
  "vrchat osc",
  "vrchat editor",
  "vrchat camera",
  "vrchat physics",
  "vrchat world",
  "vrchat prefab",
  "vrchat gimmick",
  "vrchat locomotion",
  "vrchat toggle",
  "vrchat constraint",
  "vrchat audio",
  "vrchat flight",
  "vrchat menu",
  "vrchat setup",
  "vrchat prop system",
  "vrchat physbone",
  "avatar dynamics vrchat",
  "vrchat ragdoll",
  "vrchat facetracking"
];

export const GUMROAD_STOREFRONT_SEEDS = [
  "https://vrlabs.gumroad.com",
  "https://dreadrith.gumroad.com",
  "https://architechvr.gumroad.com",
  "https://aleasevr.gumroad.com",
  "https://markcreator.gumroad.com",
  "https://rollthered.gumroad.com",
  "https://hfcred.gumroad.com",
  "https://phasedragon.gumroad.com",
  "https://hai-vr.gumroad.com",
  "https://lyuma.gumroad.com",
  "https://jessycat92.gumroad.com",
  "https://boopdoodle.gumroad.com",
  "https://zenithvr.gumroad.com",
  "https://raicovr.gumroad.com",
  "https://vrfluff.gumroad.com",
  "https://liindy.gumroad.com",
  "https://ktecharms.gumroad.com",
  "https://heartmarksman.gumroad.com",
  "https://anmeire.gumroad.com",
  "https://aparche.gumroad.com",
  "https://legacytwotails.gumroad.com",
  "https://rezilloryker.gumroad.com",
  "https://mcardellje.gumroad.com"
];

